config/routes.rb
Rails.application.routes.draw do

  root 'events#new'

  resources :teams
  resources :projects, except: :index
  resources :users, except: :index
  resources :events
  resources :team_requests, only: [:new, :create]

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  get 'projects', to: 'teams#index'
  get 'users', to: 'teams#index'
  get 'teams/:id/add_member', to: 'team_requests#new', as: :add_member
  get 'users/:id/report', to: 'users#report'
  get 'projects/:id/report', to: 'projects#report'
  post 'teams/:id/add_member', to: 'team_requests#create'
  post 'teams/:id/leave', to: 'teams#leave', as: :leave_team
  post 'team_requests/accept', to: 'team_requests#accept', as: :accept_team
  post 'team_requests/decline', to: 'team_requests#decline', as: :decline_team
  post 'projects/allocate', to: 'projects#allocate', as: :allocations
  delete 'signout', to: 'sessions#destroy'
  delete 'projects/:id/deallocate', to: 'projects#deallocate', as: :deallocations

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_teams
  has_many :teams, -> { uniq }, through: :user_teams
  has_many :projects, -> { uniq }, through: :teams
  has_many :events, -> { uniq }
  has_many :team_requests, class_name: 'TeamRequest', foreign_key: 'target_id'
  has_many :sent_requests, class_name: 'TeamRequest', foreign_key: 'source_id'
  has_many :allocations

  has_secure_password

  validates :password, length: { minimum: 4 },
    format: { with: /([A-Z]\D*\d|\d\D*[A-Z])/,
              message: "must contain at least one capital letter and one number" }
  validates :email, uniqueness: true, presence: true
  validates_format_of :email, :with => /@/

  def recent_teams
    teams.joins(:projects).order(updated_at: :desc)
  end

  def pending_requests
    pending = TeamRequest.pending_for(self.id)
    changed = TeamRequest.changed_status_for(self.id)
    message = request_message(pending, changed)
    changed.each { |r| r.destroy! }
    { pending: pending, message: message, display: pending.count > 0 }
  end

  def team_member?(user)
    user.id == self.id || !(team_ids(user) & team_ids(self)).empty?
  end

  def shared_teams_with(user)
    user.teams & self.teams
  end

  def shared_projects_with(user)
    user.projects & self.projects
  end

  def hours_between(start_date, end_date)
    hours = { total: 0, projects: Hash.new(0) }
    events.map do |e|
      if e.start > start_date.beginning_of_day && e.end < end_date.end_of_day
        hours[:total] += e.duration
        hours[:projects][e.title.to_sym] += e.duration
      end
    end
    return hours
  end

  private
  def request_message(pending, changed)
    if !changed.empty?
      message = "Team requests you have sent have changed"
      changed.each { |r| message << "; #{Team.name_for_id(r.team_id)}: #{User.find_by(id:r.target_id).forename} #{r.status}" }
    elsif !pending.empty?
      message = "You have pending team requests"
      pending.each { |r| message << "; #{Team.name_for_id(r.team_id)}" }
    end
    message
  end

  def team_ids(user)
    user.teams.map{ |t| t.id }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ReportHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy, :report]
  before_action :ensure_that_signed_in, except: [:new, :create]
  before_action :ensure_authority, only: [:edit, :update, :destroy]

  # GET /users/1
  # GET /users/1.json
  def show
    @teams = @user.shared_teams_with(current_user).sort_by{ |t| t.updated_at }.reverse!
    @projects = @user.shared_projects_with(current_user).sort_by{ |p| p.updated_at }.reverse!
    @requests = current_user.pending_requests
    if !@requests[:message].nil? then flash.now[:notice] = @requests[:message] end
    render status: :frobidden, text: 'Forbidden access' unless @user.team_member? current_user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.teams << Team.create(name: 'Personal projects')
        session[:user_id] = @user.id
        render_success format, 'created', :created
      else
        render_errors(format, @user.errors, :new)
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        render_success format, 'updated', :ok
      else
        render_errors(format, @user.errors, :edit)
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to signin_path, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /users/1/generate_report
  def report
    create_report_for params, @user
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:forename, :surname, :email, :password, :password_confirmation)
  end

  def render_success(format, action, status)
    format.html { redirect_to @user, notice: "Account was successfully #{action}." }
    format.json { render :show, status: status, location: @user }
  end

  def ensure_authority
    redirect_to :back, notice: 'Forbidden action' if @user != current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :forename %><br>
        <%= f.text_field :forename %>
    </div>
    <div class="field">
        <%= f.label :surname %><br>
        <%= f.text_field :surname %>
    </div>
    <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </div>
    <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation  %>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/users/edit.html.erb
<br>
<%= form_for @user, html: {class: 'form-inline'} do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :new_password %><br />
        <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit 'Change password', class: 'btn btn-default' %>
        <%= link_to 'Never mind', @user, class: 'btn btn-default' %>
    </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Forename</th>
      <th>Surname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.forename %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h3>Sign up for an account</h3>

<%= render 'form' %>

app/views/users/report.html.erb
<h1>Personal report</h1>
<p><strong>Name: </strong><%= @user.forename %> <%= @user.surname %> (<%= @user.email %>)</p>
<p><strong>Time: </strong><%= @start.strftime("%d.%m.%Y") %> - <%= @end.strftime("%d.%m.%Y") %></p>
<p><strong>Total hours: </strong><%= sprintf "%.1f", @hours[:total] %> h</p>
<table>
    <tr>
        <td><h3>Projects:</h3></td>
    </tr>
    <% @hours[:projects].each do |project| %>
     <tr>
        <td></td>
        <td><%= project[0] %> &nbsp; &nbsp; </td>
        <td><%= sprintf "%.1f", project[1] %> hours</td>
     </tr>
    <% end %>
</table>

app/views/users/show.html.erb
<div class="col-md-6">
<h3>User information</h3>
<p>
<strong>Name:</strong>
<%= @user.forename %> <%= @user.surname %>
</p>

<p>
<strong>Email:</strong>
<%= @user.email %>
</p>
</div>

<div class="col-md-6">
    <br>
    <%= link_to 'Change password', edit_user_path(@user), class: 'btn btn-default' unless @user != current_user %>
    <%= link_to 'Delete account', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' unless @user != current_user %>
</div>
<div class="col-md-12">
    <%= form_tag("#{@user.id}/report.pdf", { class:'form-inline', method: :get, format: 'pdf'}) do %>
    <div class="form-group">
        <%= text_field_tag :start_time, '', class: 'form-control datepicker-no-hours', placeholder: 'Beginning from' %>
    </div>
    <div class="form-group">
        <%= text_field_tag :end_time, '', class: 'form-control datepicker-no-hours', placeholder: 'until' %>
    </div>
    <div class="form-group">
        <%= submit_tag 'Generate report', class: 'btn btn-default' %>
    </div>
<% end %>
</div>
<% if @requests[:display] %>
    <div class="col-md-12 well">
        <div class="col-md-2">
            <p><strong>Pending team requests:</strong></p>
        </div>
        <div class="col-md-10">
            <% @requests[:pending].each do |pending| %>
                <p>
                <%= Team.find_by(id: pending.team_id).name %>
                <%= link_to 'Accept', accept_team_path(id: pending.id, team_id: pending.team_id), method: :post, class: 'btn btn-default btn-xs' %>
                <%= link_to 'Decline', decline_team_path(id: pending.id), method: :post, class: 'btn btn-danger btn-xs' %>
                </p>
            <% end %>
        </div>
    </div>
<% end %>

<div class="col-md-12 well">
    <div class="col-md-2">
        <p><strong>Teams:</strong></p>
    </div>
    <div class="col-md-10">
        <% @teams.each do |team| %>
            <p><%= link_to team.name, team %></p>
        <% end %>
    </div>
</div>

<div class="col-md-12 well">
    <div class="col-md-2">
        <p><strong>Projects:</strong></p>
    </div>
    <div class="col-md-10">
        <% @projects.each do |project| %>
            <p><%= link_to project.name, project %></p>
        <% end %>
    </div>
</div>