config/routes.rb
Rails.application.routes.draw do

  root 'events#new'

  resources :teams
  resources :projects, except: :index
  resources :users, except: :index
  resources :events
  resources :team_requests, only: [:new, :create]

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  get 'projects', to: 'teams#index'
  get 'users', to: 'teams#index'
  get 'teams/:id/add_member', to: 'team_requests#new', as: :add_member
  get 'users/:id/report', to: 'users#report'
  get 'projects/:id/report', to: 'projects#report'
  post 'teams/:id/add_member', to: 'team_requests#create'
  post 'teams/:id/leave', to: 'teams#leave', as: :leave_team
  post 'team_requests/accept', to: 'team_requests#accept', as: :accept_team
  post 'team_requests/decline', to: 'team_requests#decline', as: :decline_team
  post 'projects/allocate', to: 'projects#allocate', as: :allocations
  delete 'signout', to: 'sessions#destroy'
  delete 'projects/:id/deallocate', to: 'projects#deallocate', as: :deallocations

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :project_id, presence: true
  validates_datetime :end, after: :start

  def title
    Project.name_for(self.project_id)
  end

  def duration
    (self.end - self.start) / 3600
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include DateHelper
  before_action :ensure_that_signed_in
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_projects, only: [:new, :show, :edit, :create, :update]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    begin
      start = DateTime.parse(params[:start]) 
    rescue
      return redirect_to new_event_path, alert: "Incorrect start time"
    end
    endTime = start + parseDuration(params[:time]).minutes
    @event = Event.new(start: start, end: endTime, project_id: params[:project])

    respond_to do |format|
      if @event.save
        current_user.events << @event
        render_success(format, 'created', :created)
      else
        render_errors(format, @event.errors, :new)
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        render_success(format, 'updated', :ok)
      else
        render_errors(format, @event.errors, :edit)
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = current_user.events.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:start, :end, :time, :project, :project_id, :user_id)
  end

  def set_projects
    @projects = current_user.projects.all
  end

  def render_success(format, action, status)
    format.html { redirect_to @event, notice: "Event was successfully #{action}." }
    format.json { render :show, status: status, location: @event }
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: {class: 'form'} do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :project_id %><br>
      <%= f.select :project_id, options_from_collection_for_select(@projects, :id, :name, selected: @event.project.id), {}, {class:'select2'} %>
    </div>
    <div class="form-group">
    <%= f.label :start %><br>
    <%= f.datetime_select :start, {}, html: {class: 'form-control'} %>
    </div>
    <div class="form-group">
    <%= f.label :end %><br>
    <%= f.datetime_select :end, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.submit 'Done', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h3>Edit Event</h3>

<%= render 'form' %>

app/views/events/index.html.erb
<br>
<div id='calendar'></div>

app/views/events/new.html.erb
<br>
<%= form_for @event, html: {class: 'form-inline'} do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
                <% @event.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= label_tag :project %><br>
        <%= select_tag :project,
            options_from_collection_for_select(@projects, :id, :name, selected: @event.project),
            class:'select2 form-control' %>
    </div>
    <div class="form-group">
        <%= label_tag :start, 'Starting from' %><br>
        <%= text_field_tag :start, '', class: 'form-control datepicker', id: 'event-start' %>
    </div>
    <div class="form-group">
        <%= label_tag :time, 'Time spent' %><br>
        <%= text_field_tag :time, '', class: 'form-control', id: 'event-duration',
            data: { placement: 'bottom', toggle: 'tooltip',
                    title: 'Examples: 45min, 3 h 40 min, 2h, 1.5 h' }  %>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/events/show.html.erb
<div class="col-md-5">
<h3><%= @event.project.name %> event</h3>
<p>
    <strong>Date:</strong>
    <%= @event.start.strftime("%A %d.%m.%Y") %>
</p>
<p>
    <strong>Time:</strong>
    <%= @event.start.strftime("%H:%M") %> - <%= @event.end.strftime("%H:%M") %>
    (<%= sprintf "%.1f", @event.duration %> h)
</p>
<p>
    <strong>Belongs to:</strong>
    <%= link_to @event.project.name, @event.project %>
    (<%= link_to @event.project.team.name, @event.project.team %>)
</p>
</div>
<div class="col-md-7">
    <br>
<%= link_to 'Edit event', edit_event_path(@event), class: 'btn btn-default' %>
<%= link_to 'Delete event', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>