config/routes.rb
Rails.application.routes.draw do

  root 'events#new'

  resources :teams
  resources :projects, except: :index
  resources :users, except: :index
  resources :events
  resources :team_requests, only: [:new, :create]

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  get 'projects', to: 'teams#index'
  get 'users', to: 'teams#index'
  get 'teams/:id/add_member', to: 'team_requests#new', as: :add_member
  get 'users/:id/report', to: 'users#report'
  get 'projects/:id/report', to: 'projects#report'
  post 'teams/:id/add_member', to: 'team_requests#create'
  post 'teams/:id/leave', to: 'teams#leave', as: :leave_team
  post 'team_requests/accept', to: 'team_requests#accept', as: :accept_team
  post 'team_requests/decline', to: 'team_requests#decline', as: :decline_team
  post 'projects/allocate', to: 'projects#allocate', as: :allocations
  delete 'signout', to: 'sessions#destroy'
  delete 'projects/:id/deallocate', to: 'projects#deallocate', as: :deallocations

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :team
  has_many :events, dependent: :destroy
  has_many :users, -> { uniq }, through: :team
  has_many :allocations

  validates :team_id, presence: true
  validates :name, presence: true

  def self.name_for(id)
    Project.find_by(id:id).name
  end

  def total_hours_used
    self.events.inject(0) { |sum, e| sum + e.duration }
  end

  def hours_used_by_user
    hours = create_hours_hash
    self.events.map do |e|
      user = User.find_by id: e.user_id
      hours[user.id][:hours] += e.duration
    end
    add_allocations hours
  end

  def hours_between(start_time, end_time)
    hours = Hash.new
    hours[:users] = {}
    total_hours = 0;
    users.each do |u|
      hours_by_user = u.hours_between(start_time, end_time)[:projects][self.name.to_sym]
      hours[:users]["#{u.forename} #{u.surname}"] = hours_by_user
      total_hours += hours_by_user
    end
    hours[:total] = total_hours
    hours
  end

  private
  def create_hours_hash
    hours = {}
    self.users.each do |user|
      hours[user.id] = { name: "#{user.forename} #{user.surname}", hours: 0, id: user.id }
    end
    hours
  end

  def add_allocations(hours)
    total = self.total_hours_used
    hours.map do |user|
      alloc = Allocation.find_by project_id: self.id, user_id: user[1][:id]
      if alloc.nil?
        user[1][:percent] = calc_percentages user[1][:hours], total
      else
        add_percentages_by_allocations user, alloc.alloc_hours
      end
    end
    hours
  end

  def calc_percentages(hours, total)
    if total.zero?
      return 0
    end
    return hours / total * 100
  end

  def add_percentages_by_allocations(user, alloc)
    user[1][:alloc_hours] = alloc.to_s
    user[1][:percent] = calc_percentages user[1][:hours], alloc.to_f
    if user[1][:percent] > 100
      user[1][:over] = calc_percentages user[1][:hours] - alloc.to_f, user[1][:hours]
      user[1][:percent] = calc_percentages alloc.to_f, user[1][:hours]
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ReportHelper
  before_action :ensure_that_signed_in
  before_action :set_project, only: [:show, :edit, :hours, :update, :destroy, :report]
  before_action :set_teams, only: [:new, :edit, :create, :update]
  before_action :set_allocation, only: [:allocate, :deallocate]

  # GET /projects/new
  def new
    @project = Project.new
    if params[:team] then @project.team_id = params[:team] end
  end

  # GET /projects/1/edit
  def edit
  end

  # GET /projects/1/show
  def show
    @total_hours = @project.total_hours_used
    @allocation = Allocation.new
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        @project.team.touch
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        render_errors(format, @project.errors, :new)
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        @project.team.touch
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        render_errors(format, @project.errors, :edit)
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST projects/allocate
  def allocate
    if @allocation.nil?
      @allocation = Allocation.new(allocation_params)
    else
      @allocation.update(allocation_params)
    end

    if @allocation.save
      redirect_to :back, notice: "#{params[:alloc_hours]} hours allocated for #{params[:name]}"
    else
      flash[:error] = "Error in hours format, nothing allocated!"
      redirect_to :back
    end
  end

  # DELETE projects/allocate
  def deallocate
    @allocation.destroy
    redirect_to :back, notice: "Allocations for #{params[:name]} removed"
  end

  # GET /projects/1/generate_report
  def report
    create_report_for params, @project
  end

  private
  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :team_id)
  end

  def allocation_params
    params.permit(:user_id, :project_id, :alloc_hours)
  end

  def set_teams
    @teams = current_user.teams.all
  end

  def set_allocation
    @allocation = Allocation.find_by project_id:params[:project_id], user_id:params[:user_id]
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, html: {class: 'form-inline'} do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

            <ul>
                <% @project.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :team_id %><br>
        <%= f.select :team_id, options_from_collection_for_select(@teams, :id, :name, selected: @project.team_id), {}, {class:'select2'} %>
        <%= f.submit 'Done', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<h3>Your projects</h3>

<% @projects.each do |project| %>
        <p><%= link_to project.name, project %></p>
<% end %>

<br>

<%= link_to 'Create new Project', new_project_path, class: 'btn btn-default' %>

app/views/projects/new.html.erb
<h3>Create a new Project</h3>

<%= render 'form' %>

app/views/projects/report.html.erb
<h1><%= @project.name %> report</h1>
<p><strong>Team: </strong><%= @project.team.name %></p>
<p><strong>Time: </strong><%= @start.strftime("%d.%m.%Y") %> - <%= @end.strftime("%d.%m.%Y") %></p>
<p><strong>Total hours: </strong><%= sprintf "%.1f", @hours[:total] %> h</p>
<table>
    <tr>
        <td><h3>Hours used by team member:</h3></td>
    </tr>
    <% @hours[:users].each do |user| %>
     <tr>
        <td></td>
        <td><%= user[0] %> &nbsp; &nbsp; </td>
        <td><%= sprintf "%.1f", user[1] %> hours</td>
     </tr>
    <% end %>
</table>

app/views/projects/show.html.erb
<div class="col-md-8">
<h3><%= @project.name %></h3>
<p>
<strong>Team:</strong>
<%= link_to @project.team.name, @project.team %>
</p>
<p>
<strong>Total hours used:</strong>
<%= sprintf "%.1f", @project.total_hours_used %> h
</p>
</div>
<div class="col-md-4">
    <br>
    <%= link_to 'Edit project', edit_project_path(@project), class: 'btn btn-default' %>
    <%= link_to 'Delete project', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>
<div class="col-md-12 well">
    <%= form_tag("#{@project.id}/report.pdf", { class:'form-inline', method: :get, format: 'pdf'}) do %>
    <div class="form-group">
        <%= text_field_tag :start_time, '', class: 'form-control datepicker-no-hours', placeholder: 'Beginning from' %>
    </div>
    <div class="form-group">
        <%= text_field_tag :end_time, '', class: 'form-control datepicker-no-hours', placeholder: 'until' %>
    </div>
    <div class="form-group">
        <%= submit_tag 'Generate report', class: 'btn btn-default' %>
    </div>
<% end %>
</div>
<div class="col-md-12">
    <h4>Allocate hours</h4>
    <% @project.hours_used_by_user.each do |user| %>
        <div class="col-md-12">
            <div class="col-md-2 no-wrap">
                <%= link_to user[1][:name], user_path(user[1][:id]) %>
            </div>
            <div class="col-md-5">
                <div class="progress">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%= user[1] %>" aria-valuemin="0" aria-valuemax="<%= @project.total_hours_used %>" style="width: <%= user[1][:percent] %>%;">
                        <%= sprintf "%.1f", user[1][:hours] %>h
                        <% if !user[1][:alloc_hours].nil? %>
                            / <%= user[1][:alloc_hours] %>h
                        <% end %>
                    </div>
                    <% if !user[1][:alloc_hours].nil? %>
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="<%= user[1] %>" aria-valuemin="0" aria-valuemax="<%= @project.total_hours_used %>" style="width: <%= user[1][:over] %>%;"></div>
                    <% end %>
                </div>
            </div>
            <div class="col-md-2">
                <%= form_for @allocation, html: {class: 'form-inline'} do |f| %>
                    <%= hidden_field_tag :user_id, user[1][:id] %>
                    <%= hidden_field_tag :project_id, @project.id %>
                    <%= hidden_field_tag :name, user[1][:name] %>
                    <div class="form-group">
                        <%= label_tag :hours, 'Allocate hours', class: 'sr-only' %>
                        <div class="input-group no-wrap">
                            <%= text_field_tag :alloc_hours, user[1][:alloc_hours], class: 'form-control form-xs', id: "allocate-#{user[1][:id]}", placeholder: 'Allocate hours', style: 'width: 80%' %>
                            <%= button_tag(type: 'submit', id: "button-#{user[1][:id]}", class: "input-group-addon form-xs btn btn-default") do %>
                                <%= fa_icon 'history' %>
                             <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="col-md-2">
                <% if !user[1][:alloc_hours].nil? %>
                <%= form_tag deallocations_path(@project), method: 'DELETE' do %>
                    <%= hidden_field_tag :user_id, user[1][:id] %>
                    <%= hidden_field_tag :project_id, @project.id %>
                    <%= hidden_field_tag :name, user[1][:name] %>
                    <div class="form-group">
                        <%= button_tag(type: 'submit', class: 'btn btn-danger form-xs', id: "deallocate-#{user[1][:id]}") do %>
                            <%= fa_icon 'trash-o' %>
                        <% end %>
                    </div>
                <% end %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>