config/routes.rb
Rails.application.routes.draw do

  root 'events#new'

  resources :teams
  resources :projects, except: :index
  resources :users, except: :index
  resources :events
  resources :team_requests, only: [:new, :create]

  resource :session, only: [:new, :create, :delete]

  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  get 'projects', to: 'teams#index'
  get 'users', to: 'teams#index'
  get 'teams/:id/add_member', to: 'team_requests#new', as: :add_member
  get 'users/:id/report', to: 'users#report'
  get 'projects/:id/report', to: 'projects#report'
  post 'teams/:id/add_member', to: 'team_requests#create'
  post 'teams/:id/leave', to: 'teams#leave', as: :leave_team
  post 'team_requests/accept', to: 'team_requests#accept', as: :accept_team
  post 'team_requests/decline', to: 'team_requests#decline', as: :decline_team
  post 'projects/allocate', to: 'projects#allocate', as: :allocations
  delete 'signout', to: 'sessions#destroy'
  delete 'projects/:id/deallocate', to: 'projects#deallocate', as: :deallocations

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if not current_user.nil? %>
    <li><%= link_to 'Add an hour', new_event_path %></li>
    <li><%= link_to 'Calendar view', events_path %></li>
    </ul><ul class='nav navbar-right navbar-nav'>
    <li><%= link_to 'Teams and projects', teams_path %></li>
    <li><%= link_to 'My page', current_user %></li>
    <li class='divider'></li>
    <li><%= link_to 'Signout', signout_path, method: :delete %></li>
<% else %>
    <li><%= link_to 'Signin', signin_path %></li>
    <li><%= link_to 'Signup', signup_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tunnit" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tunnit" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
        <div class="col-md-8 col-md-offset-2">
       <%= render 'layouts/messages' %>
       <%= yield %>
        </div>
    </main>
  </body>
</html>